# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app main.go"
bin = "./tmp/app"
include_ext = ["go", "sql"]
exclude_dir = ["database"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
