services:
  db:
    container_name: "workoutDB"
    image: postgres:14
    volumes:
      - "./database/postgres-data:/var/lib/posgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
